[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm start"
  targetPort = 4028
  port = 8888
  autoLaunch = false

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://js.stripe.com; connect-src 'self' https://api.stripe.com https://api.resend.com https://www.google-analytics.com https://www.googletagmanager.com https://*.supabase.co https://*.supabase.in wss://*.supabase.co wss://*.supabase.in https://peycheff.com/.netlify/functions/ https://peycheff.netlify.app/.netlify/functions/; img-src 'self' data: blob: https://www.google-analytics.com https://peycheff.com https://peycheff.netlify.app; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; frame-src https://js.stripe.com https://hooks.stripe.com; base-uri 'self'; form-action 'self' https://checkout.stripe.com; frame-ancestors 'none'; upgrade-insecure-requests"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Forms (if needed for contact form fallback)
[forms.contact]
  action = "/contact"
  
# Serverless functions configuration
[functions]
  # All functions will be deployed from netlify/functions/
  external_node_modules = ["@supabase/supabase-js", "resend", "stripe", "openai", "puppeteer-core"]

# Scheduled functions (configure in Netlify UI or use GitHub Actions)
# For now, use manual trigger: POST /.netlify/functions/trigger-autopublish
