-- Seed the products table with the 6 SKUs
INSERT INTO public.products (
  slug,
  title,
  description,
  price,
  platform,
  category,
  promise,
  url,
  bullets,
  included,
  license,
  tags,
  og_title,
  og_description,
  is_featured,
  sort_order
) VALUES
-- Etsy Downloads
(
  'pmu-aftercare-pro-pack',
  'PMU Aftercare Pro Pack (PL/EN/UA/RU)',
  'Complete aftercare instructions in 4 languages with custom branding',
  19,
  'etsy',
  'template',
  'Complete aftercare instructions in 4 languages',
  'https://www.etsy.com/listing/pmuaftercarepro',
  ARRAY['Professional aftercare in Polish, English, Ukrainian, Russian', 'Printable PDF formats for immediate delivery', 'Custom branding with studio information', 'Social media ready graphics for aftercare reminders'],
  ARRAY['4x Language PDFs (PL/EN/UA/RU)', 'Social media graphics pack', 'Custom branding template', 'Client consent forms'],
  'Commercial use for one studio',
  ARRAY['pmu', 'aftercare', 'multilingual', 'client-care'],
  'PMU Aftercare Pro Pack - 4 Languages',
  'Professional permanent makeup aftercare instructions in Polish, English, Ukrainian, and Russian. Ready-to-use PDFs for your studio.',
  true,
  1
),
(
  'notion-content-calendar',
  'Notion Content Calendar (Automation-Ready)',
  'Schedule 30 days of content in 30 minutes',
  19,
  'etsy',
  'template',
  'Pre-built content calendar with automation workflows',
  'https://www.etsy.com/listing/notioncalendar',
  ARRAY['Pre-built content calendar with automation', 'AI-powered content suggestion templates', 'Multi-platform publishing integration', 'Performance tracking dashboard'],
  ARRAY['Notion calendar template', 'Content prompt library (100+ ideas)', 'Automation workflow recipes', 'Analytics tracking setup'],
  'Personal and commercial use',
  ARRAY['notion', 'content-calendar', 'automation', 'marketing'],
  'Notion Content Calendar - Automation Ready',
  'Schedule 30 days of content in 30 minutes with this automation-ready Notion template. Includes AI prompts and workflows.',
  true,
  2
),
(
  'ai-prompt-vault',
  'AI Prompt Vault: Ads & Offers',
  '500+ copywriting prompts for instant conversions',
  15,
  'etsy',
  'template',
  'Proven copywriting prompts for ads and offers',
  'https://www.etsy.com/listing/aipromptvault',
  ARRAY['500+ proven copywriting prompts', 'Categorized by industry and conversion goal', 'ChatGPT, Claude, and Midjourney optimized', 'A/B testing frameworks included'],
  ARRAY['500+ AI prompt database', 'Industry-specific prompt sets', 'A/B testing templates', 'Performance tracking spreadsheets'],
  'Unlimited commercial use',
  ARRAY['ai-prompts', 'copywriting', 'ads', 'marketing'],
  'AI Prompt Vault - 500+ Marketing Prompts',
  '500+ proven AI prompts for ads and offers. Optimized for ChatGPT, Claude, and Midjourney. Instant copywriting library.',
  false,
  3
),

-- Whop Starters
(
  'telegram-stars-paywall',
  'Telegram Stars Paywall Mini-App Starter',
  'Launch premium content channels with Telegram Stars',
  149,
  'whop',
  'starter',
  'Complete Telegram Mini-App with Stars payments, premium content gating, and automated user management',
  'https://whop.com/products/telegram-stars-starter',
  ARRAY['Complete Telegram Mini-App with Stars payment integration', 'Premium content gating and access control', 'Automated user management and subscription handling', 'Real-time payment notifications and user onboarding'],
  ARRAY['Telegram Mini-App source code', 'Stars payment integration', 'User management dashboard', 'Premium content delivery system', 'Deployment guides and documentation'],
  'Commercial use for unlimited projects',
  ARRAY['telegram', 'stars', 'mini-app', 'paywall'],
  'Telegram Stars Paywall Starter',
  'Complete Telegram Mini-App starter with Stars payments. Launch premium content channels in minutes.',
  true,
  4
),
(
  'supabase-multitenant-rls',
  'Supabase Multi-Tenant RLS + Teams',
  'Enterprise-grade multi-tenancy in one weekend',
  149,
  'whop',
  'starter',
  'Row Level Security policies for complete data isolation, team management with role-based permissions, white-label ready architecture',
  'https://whop.com/products/supabase-multitenant',
  ARRAY['Row Level Security policies for complete data isolation', 'Team management with role-based permissions', 'White-label ready architecture', 'Subscription and billing integration hooks'],
  ARRAY['Complete Supabase schema with RLS policies', 'Team management frontend components', 'Role-based permission system', 'Subscription billing integration', 'Migration scripts and documentation'],
  'Commercial use for unlimited projects',
  ARRAY['supabase', 'multi-tenant', 'rls', 'teams'],
  'Supabase Multi-Tenant RLS Starter',
  'Enterprise-grade multi-tenancy with Row Level Security. Complete team management and role-based permissions.',
  true,
  5
),
(
  'nextjs-analytics-bridge',
  'Next.js Analytics Bridge (GA4 MP + Meta CAPI)',
  'Server-side attribution that actually converts',
  99,
  'whop',
  'starter',
  'Complete GA4 Measurement Protocol integration, Meta Conversions API with deduplication, server-side tracking for 100% attribution, privacy-compliant user identification',
  'https://whop.com/products/analytics-bridge',
  ARRAY['Complete GA4 Measurement Protocol integration', 'Meta Conversions API with deduplication', 'Server-side tracking for 100% attribution', 'Privacy-compliant user identification'],
  ARRAY['Next.js analytics middleware', 'GA4 Measurement Protocol utilities', 'Meta CAPI integration with dedup', 'Privacy-safe user hashing', 'Conversion tracking templates'],
  'Commercial use for unlimited projects',
  ARRAY['nextjs', 'analytics', 'ga4', 'meta-capi'],
  'Next.js Analytics Bridge - GA4 MP + Meta CAPI',
  'Complete server-side analytics with GA4 Measurement Protocol and Meta Conversions API. 100% attribution tracking.',
  true,
  6
);